#!/usr/bin/env python3
import os
import sys
import hashlib
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
import feedparser

OPML_FILE = "opml/feeds.opml"
DB_FILE = ".rss/articles.db"
OUTPUT_DIR = "Daily RSS"

Path(DB_FILE).parent.mkdir(exist_ok=True)
Path(OUTPUT_DIR).mkdir(exist_ok=True)

class ArticleDB:
    def __init__(self, db_file):
        self.db_file = Path(db_file)
        self.seen = set()
        if self.db_file.exists():
            with open(self.db_file, 'r') as f:
                self.seen = set(line.strip() for line in f if line.strip())

    def is_seen(self, url):
        return hashlib.md5(url.encode()).hexdigest() in self.seen

    def add(self, url):
        self.seen.add(hashlib.md5(url.encode()).hexdigest())
        with open(self.db_file, 'w') as f:
            for item in self.seen:
                f.write(f"{item}\n")

    def count(self):
        return len(self.seen)

def parse_opml(opml_file):
    sources = []
    tree = ET.parse(opml_file)
    root = tree.getroot()

    for outline in root.findall('.//outline'):
        xml_url = outline.get('xmlUrl', '')
        if xml_url:
            name = outline.get('text', outline.get('title', 'Unknown'))
            sources.append({'name': name, 'url': xml_url})

    return sources

def main():
    db = ArticleDB(DB_FILE)

    if not Path(OPML_FILE).exists():
        print(f"Error: OPML file not found: {OPML_FILE}")
        sys.exit(1)

    sources = parse_opml(OPML_FILE)
    print(f"Found {len(sources)} RSS sources")

    articles = []
    total_new = 0
    total_seen = 0

    for source in sources:
        try:
            feed = feedparser.parse(source['url'])
            for entry in feed.entries[:3]:
                link = entry.get('link', '')
                if not link or db.is_seen(link):
                    total_seen += 1
                    continue

                db.add(link)
                total_new += 1

                article = {
                    'blog': source['name'],
                    'title': entry.get('title', 'No title'),
                    'link': link,
                    'desc': entry.get('description', '')[:150],
                    'date': entry.get('published', '')
                }
                articles.append(article)
        except Exception as e:
            print(f"Error fetching {source['name']}: {e}", file=sys.stderr)

    # Generate markdown
    date_str = datetime.now().strftime("%Y-%m-%d")
    time_str = datetime.now().strftime("%H:%M")
    filepath = Path(OUTPUT_DIR) / f"RSS摘要_{date_str}.md"

    content = f"""# RSS Daily Summary - {date_str}

> Generated: {date_str} {time_str}

## Stats

- New articles: {total_new}
- Skipped (duplicates): {total_seen}
- Total in database: {db.count()}

---

## Updates

"""

    for article in articles:
        content += f"### {article['blog']}\n\n"
        content += f"- **{article['title']}**\n"
        if article['desc']:
            content += f"  > {article['desc']}...\n"
        content += f"  > [Read]({article['link']})\n\n"

    content += f"""

---

*Auto-generated by GitHub Actions*
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"New: {total_new}, Skipped: {total_seen}, Total: {db.count()}")
    print(f"Saved to: {filepath}")

if __name__ == "__main__":
    main()
